CONNECTION_URL=jdbc:mysql://localhost:3306/gestione_corsi_inglese
LOGIN_USER=login
LOGIN_PASS=login
SEGRETERIA_USER=segreteria
SEGRETERIA_PASS=segreteria
INSEGNANTE_USER=insegnante
INSEGNANTE_PASS=insegnante